### ISSUE TITLE
Post process

### ISSUE THREAD

**Issue by jusonn** [hepesu/LineDistiller#2]
I have dots on the background on my result line image.
how did you post process to remove dots?

**Comment by hepesu** [comment]
Due to my preprocessing mistake, input with value(>230) will result  white dots. You can using following method to solve it.

Input should be preprocessed with contract stretch operation(input 0-255 to output 0-230, then rescale with 255). more simple expression could be (value/255*220)/255 or value * 0.003383. 220 is safer than 230.

This works in model_180102.h5 and model_180121.h5.
